* <2017-03-22>
** Fait:
   - relevé des points, calcul du rayon, stockage du circuit
** À faire:
   - établir la fonction distance -> courbure, de sorte qu'au second tour on puisse savoir quel rayon utiliser ?
* <2017-03-08>
** À faire:
   - Utiliser l'algorithme de base pour faire un relevé des points de sortie et les utiliser pour observer la suite des rayons de courbure pbtenus par détermination du cercle ciconscrit à trois points, on devrait voir apparaître des sous-suites de raoyns différents
* <2017-02-22>
** À faire:
   - Continuer la reflexion sur la détection de courbure à l'aide du Navigator?
* <2017-02-08>
** Fait:
   - Détection de courbure
** À faire:
   - Essayer de contrôler le différentiel de vitesse, on déctecte le rayon de courbure (même approximativement) et on en déduit le différentiel à utiliser lorsqu'on a retrouvé la ligne...
   - Conserver la direction antérieure de correction pour la recherche de la ligne
* <2017-01-25>
** Fait:
    - Étallonage très vite
** A Faire:
    - Color recognition qui marche hors de tapis (maintenant l'algo dit toujours "noir")
    - Zigaguer et changer dynamiquement la vitesse des moteurs
* <2016-12-09>
** Fait:
  - Un algorithme de suivi de ligne
  - Jalon 2 : OK
  - Jalon 3 : OK

** A faire:
   - Que l'étalonnage soit plus rapide!
   - Ajuster dynamiquement les angles et la vitesse!
* <2016-11-25>
** Fait:
   - etalonnage "distance euclidienne"
** A faire:
   - algorithme de suivi de ligne

* Pour le 18 novembre 2016 :
- phase d'apprentissage nombre variable de couleurs à choisir par l'utilisateur
- phase de reconnaissance des couleurs en fonction de celle apprises

* Lun  7 nov 2016 15:28:13 CET
- reconnaissance mais avec un seul apprentissage.
- à faire: pahse d'apprentissage ou l'on décide du nombre de couleurs à apprendre, phase de reconnaissance ou l'on tient compte de toutes les couleurs mesurées et des échantillons pour chaque couleur.

* Pour le 21 octobre 2016 : 
- monter le véhicule -> fait
- faire rouler le véhicule
	moteur prise B : roue droite
	moteur prise D : roue gauche
	capteur de couleur prise 1

* Pour le 14 octobre 2016 :
- récupérer les piéces -> fait

* Pour le 7 octobre 2016 : 
- installer un sdk -> fait 
- faire tourner le moteur -> fait
- lejos -> fait
